version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: vuln_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # python:
  #   build:
  #     context: .
  #     dockerfile: ../Dockerfile
  #   restart: always
  #   depends_on:
  #     - db
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_NAME: docker_files
  #     DB_USER: your_username
  #     DB_PASSWORD: your_password

volumes:
  postgres_data:
